#! /bin/sh

set -e

case "$1" in
	remove|upgrade|deconfigure)
		update-adtools-sdk-nonfree --uninstall || true
	;;

	purge)
		rm -Rf /var/cache/adtools-sdk
	;;

	failed-upgrade)
	;;

	*)
        	echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
